### ISSUE TITLE
Desapareció Informacion sobre Pycamp 2015 

### ISSUE THREAD

**Issue by jmansilla** [PyAr/wiki#3]
Hace algunas semanas, usando la UI web ingresé información en las siguientes urls:
- a) http://python.org.ar/wiki/PyCamp/2015/PosiblesSedes
- b) http://python.org.ar/wiki/PyCamp/2015

En a) se incluyó información sobre La Serranita

En b), además de la información sobre La Serranita, se pusieron datos concretos como fecha, y formulario de preinscripción.

**Comment by mgaitan** [comment]
@javimansilla ahi lo arreglé, los datos siempre se guardan todos, pero tenemos (sospecho que un par) de problemas 
- en waliki, cuando hay mucho cambios concurrentes, parece que puede quedar en branch detechado y generar una realidad paralela "espacio-tiempo" ;-)
- la caché del django de pyarweb  nos oculta a veces la verdad de la milanesa. 

estaremos atentos.

**Comment by javimansilla** [comment]
Gracias
