### ISSUE TITLE
Errores cuando se hace nikola build

### ISSUE THREAD

**Issue by tzulberti** [PyAr/wiki#53]
Cuando se hace `nikola clean && nikola build` aparecen muchisimos errores.

Deberiamos corregirlos

**Comment by tzulberti** [comment]
Voy a separar esto por secciones porque hay demasiados errores:

- [x]  Noticias
- [x] Recetario
- [x] Eventos
- [x]  Recursos
- [x] Charlas
- [x] Aprendiendo Python
- [x] Material
- [x] Donaciones
- [ ] pycamp

**Comment by eamanu** [comment]
Aquí también aparecen http://wiki.staging.python.org.ar/tareaspendientes/ @tzulberti

**Comment by tzulberti** [comment]
Si todavia no hice el deploy. Estoy con un issue pero hoy a la noche lo hago
