### ISSUE TITLE
Mensajes de errores en páginas de pycamp anteriores

### ISSUE THREAD

**Issue by eamanu** [PyAr/wiki#68]
Puedo ver que en el varias páginas de pycam anteriores se ven mensajes de errores:

![image](https://user-images.githubusercontent.com/7605307/77119954-62f0e280-6a16-11ea-8b46-ea4f91eb569c.png)

![image](https://user-images.githubusercontent.com/7605307/77119965-684e2d00-6a16-11ea-978d-0b0e0bb8aa60.png)

En las páginas que se ven estos mensajes son las siguientes:

* http://wiki.staging.python.org.ar/PyCamp/2017/
* http://wiki.staging.python.org.ar/PyCamp/2009/

**Comment by tzulberti** [comment]
Gracias. Eso esta relacionado al issue #55 que es reemplazar lo de GoogleMaps

**Comment by eamanu** [comment]
@tzulberti igualmente veo otros mensajes como:

![image](https://user-images.githubusercontent.com/7605307/77120559-e5c66d00-6a17-11ea-9435-1e46e86a527c.png)

(me parece que no son de google maps)

**Comment by tzulberti** [comment]
Creo que esos errores los solucione en el PR #53 pero por ahi no lo depoye

Dame un sec que me fijo

**Comment by eamanu** [comment]
@tzulberti Ahí actualicé la lista, son solo en 2017 y 2009, los mensajes que (IMO) no son del Maps

**Comment by tzulberti** [comment]
ok, gracias

**Comment by tzulberti** [comment]
Solucionado en el PR #73
