### ISSUE TITLE
Se ven mal los mails en UnManualEnCadaUniversidad

### ISSUE THREAD

**Issue by eamanu** [PyAr/wiki#69]
Veo que los mails aparecen no en formato legible

![image](https://user-images.githubusercontent.com/7605307/77121198-6afe5180-6a19-11ea-9aca-fbed7eb04b92.png)

Puede ser que el nombre del proyecto esté mal? no debería ser `UnManualEnCadaUniversidad` en vez de `Unmanualencadauniversidad`?

**Comment by eamanu** [comment]
Lo del nombre también aparece en http://wiki.staging.python.org.ar/Proyectos/usodepythonenlauniversidad/

**Comment by eamanu** [comment]
Lo del mail también lo veo aquí: http://wiki.staging.python.org.ar/Proyectos/geine/ me parece que debe ser algo de la generación de la pagina

tambien: http://wiki.staging.python.org.ar/recursos/

**Comment by tzulberti** [comment]
Que los mails se muestren con `nombre AT ULR` no esta mal. Es justamente para evitar que los scrapen y les manden mail.

Los que estan mal son los mails de `MailTo` que aparece el mail directo

**Comment by tzulberti** [comment]
Se soluciono en el PR #72
