### ISSUE TITLE
Errores en la wiki

### ISSUE THREAD

**Issue by galloramiro** [PyAr/wiki#8]
Estos son todos los que encontré en la Wiki, si se me paso uno avisen y lo agrego.

- [ ]  [wiki/Eventos](http://www.python.org.ar/wiki/Eventos) 
- `<blockquote id="reuniones">`
- `<h1>System Message: WARNING/2 (&lt;string&gt; line 44) <a href="#id5">id5</a></h1>`
- `<h1>System Message: ERROR/3 (&lt;string&gt; line 9) <a href="#id11">id11</a></h1>`

- [ ]  [wiki/ListaDeCorreos](http://www.python.org.ar/wiki/ListaDeCorreo)
- `<a href="/wiki/MailTopyar-subscribe-AT-python-DOT-org-DOT-ar">[[MailTo(pyar-subscribe AT python DOT org DOT ar)]]</a>`
- `<h1>System Message: WARNING/2 (&lt;string&gt; line 73) <a href="#id2">id2</a></h1>`
- `<h1>System Message: ERROR/3 (&lt;string&gt; line 14) <a href="#id13">id13</a></h1>`

- [ ]  [wiki/Proyectos](http://www.python.org.ar/wiki/Proyectos)
- `<a href="/wiki/Navigationchildren-1">[[Navigation(children, 1)]]</a>`
- `<h1>System Message: ERROR/3 (&lt;string&gt; line 37) <a href="#id7">id7</a></h1>`

- [ ]  [wiki/Recursos](http://www.python.org.ar/wiki/Recursos)
- `<a href="/wiki/MailTomconte-AT-atommica-DOT-com-Martin-Conte-Mac-Donell">[[MailTo(mconte AT atommica DOT com, Martín Conte Mac Donell)]]</a>`
- `<td>Por orden alfabético.</td>`

- [ ]  [wiki/Charlas](http://www.python.org.ar/wiki/Charlas)
- `<h1>System Message: WARNING/2 (&lt;string&gt; line 396)</h1>`

- [ ]  [wiki/TareasPendientes](http://www.python.org.ar/wiki/TareasPendientes)
- `<p><a href="/wiki/Navigationchildren">[[Navigation(children)]]</a></p>`
- `<div id="id3">`

- [ ]  [wiki/PreguntasFrecuentes](http://www.python.org.ar/wiki/PreguntasFrecuentes)
- `<div id="id1">`

- [ ]  [wiki/Trabajos](http://www.python.org.ar/wiki/Trabajos)
- `<h1>System Message: WARNING/2 (&lt;string&gt; line 1081) <a href="#id3">id3</a></h1>` *N

- [ ]  [wiki/Donaciones](http://www.python.org.ar/wiki/Donaciones)
- `<a href="/wiki/DineroMail">[[DineroMail()]]</a>`
- `<a href="/wiki/CuentaDigital">[[CuentaDigital()]]</a>`

- [ ]  [wiki/AdoptaUnNewbie](http://www.python.org.ar/wiki/AdoptaUnNewbie)
- `<div id="id10">`

**Comment by tzulberti** [comment]
Cierro este issue porque esa relacionado a lo isssues de build-error que solucione
