### ISSUE TITLE
Mover la wiki a Nikola

### ISSUE THREAD

**Issue by tzulberti** [PyAr/wiki#9]
Estamos teniendo varios problemas con la solución actual en la pagina de la Wiki, por lo que una opcion es convertir al wiki a un sitio statico usando Nikola.

**Comment by mgaitan** [comment]
@tzulberti este repo es el que contiene **el contenido** de la wiki. deberia ir en 
https://github.com/PyAr/pyarweb

anyway, cuál es el plan si se migra a nikola? no dejaría de ser una wiki? por qué Pyar no asume el mantenimiento/actualización de Waliki en cambio? cuales son concretamente los problemas que hay?

**Comment by gilgamezh** [comment]
Lo que estuvimos charlando es justamente que no queremos es mantener Waliki. (Por que apenas tenemos gente para hacer algunas cosas para la web claro)
Nikola es un proyecto activo que tiene comunidad, actualizaciones, etc. Y nosotros con lo poquito que tenemos de aportes enfocarnos en otras funcionalidades de la web al margen del contenido del wiki.

Y dejarle el trabajo de interactuar con los usuarios a GH.

**Comment by gilgamezh** [comment]
Mientras tanto deshabilité la edición en el sitio
- todos los POST a /wiki/* responden con un 403
- todos los GET a */edit te mandan a http://www.python.org.ar/wiki/WalikiOff
- Cambié el push por un pull cada 5 minutos. 

Por lo tanto a partir de ahora para hacer un cambio hay que:

- Crear un PR en este repo
- Ejecutar ./manage.py sync_waliki 
- Limpiar la caché de django `/manage.py clear_cache`

**Comment by tzulberti** [comment]
Cierro este issue porque al final esto lo separe en varias partes
